site_name: Chief Cloud Portal Documents

theme:
  name: material
  custom_dir: overrides/

  # 更改配色
  palette:
    - scheme: chief
      toggle:
        icon: material/brightness-7
        name: chief theme
    - scheme: default
      toggle:
        icon: material/brightness-4
        name: default theme

  # 預設語言
  language: zh-TW

  logo: assets/Chief_logo_xl.png
  favicon: assets/images/favicon.ico

  features:
    - navigation.instant
    - navigation.instant.progress
    - navigation.tabs
    - navigation.tabs.sticky

nav:
  - 首頁: "index.md"
  - 關於CCP:
      - CCP Website: "https://portal.chiefappc.com/"
  - 使用指南:
      - 建立帳戶:
          - pdf: "login.md"
          - ppt: "https://allencloud.ccis.chiefappc.com/brian/Chief%20Cloud%20Portal%E6%93%8D%E4%BD%9C%E8%AA%AA%E6%98%8E-IAM.pptx"
      - 使用操作:
          - 帳戶操作: ""
          - 資源管理: ""
          - 其他操作: ""
  - 常見問題:
      - 帳戶問題: ""
      - 功能問題: ""
      - 技術問題: ""
  - 更新日誌:
      - 最新版本: ""
      - 歷史版本: ""
  - 聯絡我們:
      - License: "license.md"
      - 關於我們: "about.md"

extra:
  # 語言切換選項
  alternate:
    - name: 繁體中文
      link: /zh-TW
      lang: zh-TW
    - name: English
      link: /en/
      lang: en

  # 移除Made with...
  generator: false

  # 外部連結
  social:
    - icon: fontawesome/brands/facebook
      link: https://www.facebook.com/chieftelecom
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/@chieftelecom9963
    - icon: fontawesome/brands/line
      link: https://page.line.me/chieftelecom
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/chieftelecom
copyright: COPYRIGHT@2020 CHIEF TELECOM INC. ALL RIGHTS RESERVED

extra_css:
  - stylesheets/extra.css
