site_name: Chief Cloud Portal Documents
site_url: https://localhost:8000/

theme:
  name: material
  custom_dir: overrides/

  # 更改配色
  palette:
    - scheme: chief
      toggle:
        icon: material/cloud
        name: chief theme
    - scheme: slate
      toggle:
        icon: material/cloud-outline
        name: default theme

  # 預設語言
  language: zh-TW

  logo: assets/Chief_logo_xl.png
  favicon: assets/images/favicon.ico

  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - toc.integrate
    - navigation.top

nav:
  - 首頁: "index.md"
  - 關於CCP:
      - CCP Website: "https://portal.chiefappc.com/"
  - 使用指南:
      - Register: "register.md"
      - VM: "vm.md"
      - VPC: "vpc.md"
      - CCIS: "ccis.md"
      - IAM:
          - markdown: iammd.md
          - pdf: "iam.md"
  - 常見問題:
      - 帳戶問題: "not_created.md"
      - 功能問題: "not_created.md"
      - 技術問題: "not_created.md"
  - 更新日誌:
      - 最新版本: "not_created.md"
      - 歷史版本: "not_created.md"
  - 聯絡我們:
      - License: "license.md"
      - 關於我們: "about.md"

extra:
  # 移除Made with...
  generator: false

  # 外部連結
  social:
    - icon: fontawesome/brands/facebook
      link: https://www.facebook.com/chieftelecom
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/@chieftelecom9963
    - icon: fontawesome/brands/line
      link: https://page.line.me/chieftelecom
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/chieftelecom

copyright: COPYRIGHT@2020 CHIEF TELECOM INC. ALL RIGHTS RESERVED

extra_css:
  - stylesheets/extra.css

# 啟用圖示和表情符號
markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - admonition
  - pymdownx.details
  - pymdownx.superfences
