site_name: CCP Docs

theme:
  name: readthedocs
  locale: zh_TW
  navigation_depth: 4
  custom_dir: custom_theme/
nav:
  - 首頁: "index.md"
  - 關於CCP:
      - CCP Website: "https://portal.chiefappc.com/"
  - 使用指南:
      - 建立帳戶:
          - pdf: "login.md"
          - ppt: "https://allencloud.ccis.chiefappc.com/brian/Chief%20Cloud%20Portal%E6%93%8D%E4%BD%9C%E8%AA%AA%E6%98%8E-IAM.pptx"
      - 使用操作:
          - 帳戶操作: ""
          - 資源管理: ""
          - 其他操作: ""
  - 常見問題:
      - 帳戶問題: ""
      - 功能問題: ""
      - 技術問題: ""
  - 更新日誌:
      - 最新版本: ""
      - 歷史版本: ""
  - 聯絡我們:
      - License: "license.md"
      - 關於我們: "about.md"
